#!/usr/bin/env python3
"""Small hosted conformance corpus exercised through the production compiler.

This is not the parser-fragment or klondike diagnostic gate. It invokes a copy
of the ordinary workspace seed, gives it source on stdin, and checks its actual
artifact and process behavior. Expected answers are hand-authored corpus data,
never generated by the compiler under test. Python is test tooling, not part of
the compiler or generated program's execution path.
The corpus covers ordinary non-directive hosted input only; leading `-- emit:`
routes are excluded.

The corpus covers checked lexical/structural rejection, accepted boundaries,
operator-class restrictions, and lowering after a direct return. Diagnostic
priority is whole-source lexing, then whole-source structural recognition,
then AST/operator-class checks, then native semantics. It does not promise the
globally earliest source error. The structural recognizer and AST builder are
still separate passes; these examples do NOT certify complete grammar/type
checking, general tail calls, allocation lifetime, or a repaired CLI.
The explicit `reject-legacy` profile pins the CURRENT rejection envelope
(status 0, stdout diagnostic and return marker), not a desirable final CLI.
Fresh directories exclude stale artifacts; the stale-output defect is not
claimed fixed by these tests. Add new profiles/tests with their actual repairs.

Usage: make compiler-conformance
       python3 bootstrap/tests/compiler_conformance.py --compiler /path/to/seed
       python3 bootstrap/tests/compiler_conformance.py --keep-work
`--compiler` is an explicit candidate/baseline experiment, never a silent env
override. It reports its digest and need not match the workspace seed checksum.
The default verifies the workspace seed against its adjacent checksum; it does
not require either file to match git HEAD (a reseeded candidate is testable).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "bootstrap/tests/fixtures/compiler_conformance.json"
SEED = ROOT / "bootstrap/seed/gen1.seed"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def unique_object(pairs: list[tuple[str, object]]) -> dict:
    obj = {}
    for key, value in pairs:
        require(key not in obj, f"duplicate JSON key {key!r}")
        obj[key] = value
    return obj


def read_corpus() -> list[dict]:
    data = json.loads(CORPUS.read_text(encoding="utf-8"), object_pairs_hook=unique_object)
    require(isinstance(data, dict), "corpus must be an object")
    require(set(data) == {"version", "scope", "cases"}, "unknown/missing corpus keys")
    require(type(data["version"]) is int and data["version"] == 1, "unsupported corpus version")
    require(isinstance(data["scope"], str) and bool(data["scope"]), "missing corpus scope")
    cases = data["cases"]
    require(isinstance(cases, list) and bool(cases), "corpus must contain cases")
    seen = set()
    profiles = set()
    for case in cases:
        require(isinstance(case, dict), "each case must be an object")
        ident = case.get("id")
        require(isinstance(ident, str) and re.fullmatch(r"[a-z][a-z0-9_-]*", ident), "invalid case id")
        require(ident not in seen, f"duplicate case id {ident}")
        seen.add(ident)
        profile = case.get("profile")
        require(profile in ("run", "reject-legacy"), f"{ident}: unknown profile {profile!r}")
        profiles.add(profile)
        specific = {"stdin", "stdout", "status"} if profile == "run" else {"diagnostic"}
        require(set(case) == {"id", "profile", "source"} | specific, f"{ident}: unknown/missing case keys")
        for field in ({"source", "stdin", "stdout"} if profile == "run" else {"source", "diagnostic"}):
            require(isinstance(case[field], str), f"{ident}: {field} must be text")
            case[field].encode("utf-8")  # Reject unencodable surrogate data before running anything.
        require(bool(case["source"]), f"{ident}: empty source fixture")
        if profile == "run":
            require(type(case["status"]) is int and 0 <= case["status"] <= 255, f"{ident}: invalid exit status")
        else:
            require(re.fullmatch(r"line [1-9][0-9]*: [^\r\n]+ \(ERR [0-9]{3}\)", case["diagnostic"]),
                    f"{ident}: expected one located diagnostic")
    require(profiles == {"run", "reject-legacy"}, "corpus must retain both accept and reject controls")
    return cases


def require_elf(path: Path) -> None:
    require(path.is_file() and not path.is_symlink(), f"missing regular ELF: {path}")
    with path.open("rb") as source:
        head = source.read(20)
    require(len(head) == 20 and head[:6] == b"\x7fELF\x02\x01" and head[18:20] == b"\x3e\x00",
            f"not an x86-64 little-endian ELF: {path}")


def copy_compiler(source: Path, work: Path, verify_checksum: bool) -> Path:
    require_elf(source)
    binary = work / "compiler"
    shutil.copyfile(source, binary)
    digest = hashlib.sha256(binary.read_bytes()).hexdigest()
    if verify_checksum:
        fields = SEED.with_suffix(".seed.sha256").read_text(encoding="ascii").split()
        require(len(fields) == 2 and fields[1] == "gen1.seed" and fields[0] == digest,
                "workspace seed checksum mismatch")
    binary.chmod(0o700)
    print(f"compiler-conformance: compiler={source} sha256={digest} mode={'checksum-verified-workspace' if verify_checksum else 'explicit'}", flush=True)
    return binary


def invoke(binary: Path, data: bytes, directory: Path, phase: str, timeout: float) -> subprocess.CompletedProcess:
    try:
        result = subprocess.run([str(binary)], input=data, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, cwd=directory, timeout=timeout, check=False)
    except subprocess.TimeoutExpired as error:
        (directory / f"{phase}.stdout").write_bytes(error.stdout or b"")
        (directory / f"{phase}.stderr").write_bytes(error.stderr or b"")
        (directory / f"{phase}.status").write_text("TIMEOUT\n", encoding="ascii")
        raise ValueError(f"{phase} timed out after {timeout:g}s") from error
    (directory / f"{phase}.stdout").write_bytes(result.stdout)
    (directory / f"{phase}.stderr").write_bytes(result.stderr)
    (directory / f"{phase}.status").write_text(f"{result.returncode}\n", encoding="ascii")
    return result


def exact(actual: object, expected: object, label: str) -> None:
    require(actual == expected, f"{label}: expected {expected!r}, got {actual!r}")


def check_case(case: dict, compiler: Path, work: Path, timeout: float) -> None:
    directory = work / case["id"]
    directory.mkdir()  # Never reuse a directory containing a stale a.out.
    source = case["source"].encode("utf-8")
    (directory / "source.herb").write_bytes(source)
    result = invoke(compiler, source, directory, "compile", timeout)
    artifact = directory / "a.out"
    exact(result.returncode, 0, "compiler status")
    exact(result.stderr, b"", "compiler stderr")
    if case["profile"] == "reject-legacy":
        # A crash, a different diagnostic, duplicate messages, or an output
        # artifact is not a successful rejection. Preserve the legacy envelope
        # explicitly until a separate change establishes a new CLI contract.
        exact(result.stdout, (case["diagnostic"] + "\n0\n").encode("utf-8"), "compiler diagnostic")
        require(not artifact.exists() and not artifact.is_symlink(), "rejected source produced a.out")
        return
    exact(result.stdout, b"0\n", "compiler stdout")
    require_elf(artifact)
    artifact.chmod(0o700)
    result = invoke(artifact, case["stdin"].encode("utf-8"), directory, "run", timeout)
    exact(result.returncode, case["status"], "program status")
    exact(result.stdout, case["stdout"].encode("utf-8"), "program stdout")
    exact(result.stderr, b"", "program stderr")


def positive_timeout(value: str) -> float:
    timeout = float(value)
    if not math.isfinite(timeout) or timeout <= 0:
        raise argparse.ArgumentTypeError("timeout must be finite and positive")
    return timeout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--compiler", type=Path, help="explicit candidate/baseline ELF; default is checksum-verified workspace seed")
    parser.add_argument("--timeout", type=positive_timeout, default=10.0, help="per-process seconds (default: 10)")
    parser.add_argument("--check-corpus", action="store_true", help="validate all corpus data without executing a compiler")
    parser.add_argument("--keep-work", action="store_true", help="retain copied compiler, source, status, streams and ELF artifacts")
    args = parser.parse_args()
    work = None
    try:
        cases = read_corpus()
        accepted = sum(case["profile"] == "run" for case in cases)
        print(f"compiler-conformance corpus: {len(cases)} cases ({accepted} run, {len(cases) - accepted} reject-legacy)", flush=True)
        if args.check_corpus:
            return 0
        work = Path(tempfile.mkdtemp(prefix="herbert-conformance."))
        compiler = copy_compiler((args.compiler or SEED).resolve(), work, args.compiler is None)
        failed = 0
        for case in cases:
            try:
                check_case(case, compiler, work, args.timeout)
                print(f"PASS: {case['id']}", flush=True)
            except (OSError, ValueError) as error:
                failed += 1
                print(f"FAIL: {case['id']}: {error}", flush=True)
        print(f"compiler-conformance: {len(cases) - failed}/{len(cases)} passed; {failed} failed", flush=True)
        return 1 if failed else 0
    except (OSError, ValueError) as error:
        print(f"FAIL: compiler-conformance setup: {error}", file=sys.stderr)
        return 1
    finally:
        if work is not None:
            if args.keep_work:
                print(f"compiler-conformance artifacts: {work}", flush=True)
            else:
                shutil.rmtree(work)


if __name__ == "__main__":
    sys.exit(main())
